"use client";

import { useEffect, useRef, useState } from "react";

/**
 * Focus audio. Six modes, all generated by WebAudio so nothing to license or
 * host. Fixed master gain — the panel intentionally has no volume.
 *
 * Modes (driven by localStorage["sound"]):
 *   "off"      — silence
 *   "pink"     — pink noise (Paul Kellet filter), broad balanced spectrum
 *   "brown"    — brown noise (random walk + lowpass 800 Hz + slow tremolo)
 *   "binaural" — 40 Hz gamma binaural beat (200 Hz L / 240 Hz R + bed)
 *   "lofi"     — warm pad: 3 detuned saws → lowpass w/ slow LFO + vinyl crackle
 *   "drone"    — cinematic: sub 55 Hz + detuned sine octave + filtered air pad
 */
export type FocusMode = "off" | "pink" | "brown" | "binaural" | "lofi" | "drone" | "storm" | "laundry";

const VALID_MODES: FocusMode[] = ["off", "pink", "brown", "binaural", "lofi", "drone", "storm", "laundry"];

function readMode(): FocusMode {
  if (typeof window === "undefined") return "off";
  const raw = localStorage.getItem("sound");
  if (raw === "true" || raw === "noise") return "brown";
  if (raw === "isochronic") return "binaural";
  if (raw === "false" || raw === null) return "off";
  return (VALID_MODES as string[]).includes(raw) ? (raw as FocusMode) : "off";
}

export function FocusAudio() {
  const [mode, setMode] = useState<FocusMode>("off");
  const stopRef = useRef<(() => void) | null>(null);

  useEffect(() => {
    if (typeof window === "undefined") return;
    setMode(readMode());

    const sync = () => setMode(readMode());
    const handleStorage = (e: StorageEvent) => {
      if (e.key === "sound") sync();
    };
    window.addEventListener("storage", handleStorage);
    window.addEventListener("sound-toggle", sync);
    return () => {
      window.removeEventListener("storage", handleStorage);
      window.removeEventListener("sound-toggle", sync);
    };
  }, []);

  useEffect(() => {
    if (typeof window === "undefined") return;

    if (mode === "off") {
      stopRef.current?.();
      stopRef.current = null;
      return;
    }

    type WebkitWindow = Window & { webkitAudioContext?: typeof AudioContext };
    const Ctx =
      window.AudioContext ?? (window as WebkitWindow).webkitAudioContext;
    if (!Ctx) return;

    const ctx = new Ctx();
    const master = ctx.createGain();
    master.gain.value = 0.05;
    master.connect(ctx.destination);

    const nodesToStop: { stop: () => void }[] = [];

    // ─── PINK NOISE ────────────────────────────────────────────────
    if (mode === "pink") {
      const bufferSize = 2 * ctx.sampleRate;
      const buf = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
      const data = buf.getChannelData(0);
      // Paul Kellet's economy pink filter.
      let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0;
      for (let i = 0; i < bufferSize; i++) {
        const white = Math.random() * 2 - 1;
        b0 = 0.99886 * b0 + white * 0.0555179;
        b1 = 0.99332 * b1 + white * 0.0750759;
        b2 = 0.96900 * b2 + white * 0.1538520;
        b3 = 0.86650 * b3 + white * 0.3104856;
        b4 = 0.55000 * b4 + white * 0.5329522;
        b5 = -0.7616 * b5 - white * 0.0168980;
        data[i] = (b0 + b1 + b2 + b3 + b4 + b5 + b6 + white * 0.5362) * 0.11;
        b6 = white * 0.115926;
      }
      const noise = ctx.createBufferSource();
      noise.buffer = buf;
      noise.loop = true;
      const g = ctx.createGain();
      g.gain.value = 1.0;
      noise.connect(g);
      g.connect(master);
      noise.start();
      nodesToStop.push(noise);
    }

    // ─── BROWN NOISE ───────────────────────────────────────────────
    if (mode === "brown") {
      const bedGain = ctx.createGain();
      bedGain.gain.value = 1.0;
      bedGain.connect(master);

      const bufferSize = 2 * ctx.sampleRate;
      const buf = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
      const data = buf.getChannelData(0);
      let lastOut = 0;
      for (let i = 0; i < bufferSize; i++) {
        const white = Math.random() * 2 - 1;
        lastOut = (lastOut + 0.02 * white) / 1.02;
        data[i] = lastOut * 3.5;
      }
      const noise = ctx.createBufferSource();
      noise.buffer = buf;
      noise.loop = true;

      const lowpass = ctx.createBiquadFilter();
      lowpass.type = "lowpass";
      lowpass.frequency.value = 800;
      lowpass.Q.value = 0.7;

      const tremoloOsc = ctx.createOscillator();
      tremoloOsc.frequency.value = 0.08;
      const tremoloDepth = ctx.createGain();
      tremoloDepth.gain.value = 0.012;
      tremoloOsc.connect(tremoloDepth);
      tremoloDepth.connect(bedGain.gain);

      noise.connect(lowpass);
      lowpass.connect(bedGain);
      noise.start();
      tremoloOsc.start();
      nodesToStop.push(noise, tremoloOsc);
    }

    // ─── BINAURAL γ ────────────────────────────────────────────────
    if (mode === "binaural") {
      // Bed under the tonal beat for warmth.
      const bedGain = ctx.createGain();
      bedGain.gain.value = 0.45;
      bedGain.connect(master);

      const bufferSize = 2 * ctx.sampleRate;
      const buf = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
      const data = buf.getChannelData(0);
      let lastOut = 0;
      for (let i = 0; i < bufferSize; i++) {
        const white = Math.random() * 2 - 1;
        lastOut = (lastOut + 0.02 * white) / 1.02;
        data[i] = lastOut * 3.5;
      }
      const noise = ctx.createBufferSource();
      noise.buffer = buf;
      noise.loop = true;
      const lowpass = ctx.createBiquadFilter();
      lowpass.type = "lowpass";
      lowpass.frequency.value = 800;
      noise.connect(lowpass);
      lowpass.connect(bedGain);
      noise.start();
      nodesToStop.push(noise);

      // 40 Hz gamma: 200 Hz L / 240 Hz R.
      const merger = ctx.createChannelMerger(2);
      const toneGain = ctx.createGain();
      toneGain.gain.value = 0.55;
      merger.connect(toneGain);
      toneGain.connect(master);

      const left = ctx.createOscillator();
      left.frequency.value = 200;
      const leftGain = ctx.createGain();
      leftGain.gain.value = 1;
      left.connect(leftGain);
      leftGain.connect(merger, 0, 0);

      const right = ctx.createOscillator();
      right.frequency.value = 240;
      const rightGain = ctx.createGain();
      rightGain.gain.value = 1;
      right.connect(rightGain);
      rightGain.connect(merger, 0, 1);

      left.start();
      right.start();
      nodesToStop.push(left, right);
    }

    // ─── LO-FI PAD ─────────────────────────────────────────────────
    if (mode === "lofi") {
      // Warm pad: A2 root with detuned saw stack, lowpassed, slow filter LFO.
      // Root = 110 Hz (A2). Stack: -7c, +5c on top of root for chorus thickness.
      const padGain = ctx.createGain();
      padGain.gain.value = 0.5;
      const lowpass = ctx.createBiquadFilter();
      lowpass.type = "lowpass";
      lowpass.frequency.value = 1400;
      lowpass.Q.value = 1.2;
      padGain.connect(lowpass);
      lowpass.connect(master);

      const detunes = [-7, 0, 5];
      for (const cents of detunes) {
        const osc = ctx.createOscillator();
        osc.type = "sawtooth";
        osc.frequency.value = 110;
        osc.detune.value = cents;
        const g = ctx.createGain();
        g.gain.value = 0.33;
        osc.connect(g);
        g.connect(padGain);
        osc.start();
        nodesToStop.push(osc);
      }

      // Add a perfect 5th sub-octave for grounding.
      const sub = ctx.createOscillator();
      sub.type = "sine";
      sub.frequency.value = 55;
      const subGain = ctx.createGain();
      subGain.gain.value = 0.18;
      sub.connect(subGain);
      subGain.connect(master);
      sub.start();
      nodesToStop.push(sub);

      // Slow filter sweep LFO so the pad breathes.
      const lfo = ctx.createOscillator();
      lfo.type = "sine";
      lfo.frequency.value = 0.06;
      const lfoDepth = ctx.createGain();
      lfoDepth.gain.value = 500;
      lfo.connect(lfoDepth);
      lfoDepth.connect(lowpass.frequency);
      lfo.start();
      nodesToStop.push(lfo);

      // Sparse vinyl crackle: highpassed brown noise at low volume.
      const crackleBuf = ctx.createBuffer(1, ctx.sampleRate, ctx.sampleRate);
      const cd = crackleBuf.getChannelData(0);
      let last = 0;
      for (let i = 0; i < cd.length; i++) {
        const w = Math.random() * 2 - 1;
        last = (last + 0.02 * w) / 1.02;
        // Random pops on top of the bed.
        cd[i] = last * 2 + (Math.random() < 0.0002 ? (Math.random() * 2 - 1) * 0.4 : 0);
      }
      const crackle = ctx.createBufferSource();
      crackle.buffer = crackleBuf;
      crackle.loop = true;
      const hp = ctx.createBiquadFilter();
      hp.type = "highpass";
      hp.frequency.value = 1800;
      const cg = ctx.createGain();
      cg.gain.value = 0.18;
      crackle.connect(hp);
      hp.connect(cg);
      cg.connect(master);
      crackle.start();
      nodesToStop.push(crackle);
    }

    // ─── CINEMATIC DRONE ──────────────────────────────────────────
    if (mode === "drone") {
      const droneGain = ctx.createGain();
      droneGain.gain.value = 0.55;
      droneGain.connect(master);

      // Sub fundamental: A1.
      const sub = ctx.createOscillator();
      sub.type = "sine";
      sub.frequency.value = 55;
      const subGain = ctx.createGain();
      subGain.gain.value = 0.5;
      sub.connect(subGain);
      subGain.connect(droneGain);
      sub.start();
      nodesToStop.push(sub);

      // Detuned octave above for slow beating.
      const t1 = ctx.createOscillator();
      t1.type = "sine";
      t1.frequency.value = 110;
      const t1g = ctx.createGain();
      t1g.gain.value = 0.32;
      t1.connect(t1g);
      t1g.connect(droneGain);
      t1.start();
      nodesToStop.push(t1);

      const t2 = ctx.createOscillator();
      t2.type = "sine";
      t2.frequency.value = 110.6;
      const t2g = ctx.createGain();
      t2g.gain.value = 0.32;
      t2.connect(t2g);
      t2g.connect(droneGain);
      t2.start();
      nodesToStop.push(t2);

      // Air pad: bandpassed white noise that breathes.
      const airBufSize = 2 * ctx.sampleRate;
      const airBuf = ctx.createBuffer(1, airBufSize, ctx.sampleRate);
      const airData = airBuf.getChannelData(0);
      for (let i = 0; i < airBufSize; i++) airData[i] = Math.random() * 2 - 1;
      const air = ctx.createBufferSource();
      air.buffer = airBuf;
      air.loop = true;
      const bp = ctx.createBiquadFilter();
      bp.type = "bandpass";
      bp.frequency.value = 900;
      bp.Q.value = 3.5;
      const airGain = ctx.createGain();
      airGain.gain.value = 0.6;
      air.connect(bp);
      bp.connect(airGain);
      airGain.connect(droneGain);
      air.start();
      nodesToStop.push(air);

      // Very slow LFO on the bandpass for the breathing.
      const lfo = ctx.createOscillator();
      lfo.type = "sine";
      lfo.frequency.value = 0.04;
      const lfoDepth = ctx.createGain();
      lfoDepth.gain.value = 400;
      lfo.connect(lfoDepth);
      lfoDepth.connect(bp.frequency);
      lfo.start();
      nodesToStop.push(lfo);
    }

    // ─── COZY DOOM RUMBLE (storm) ─────────────────────────────────
    // Smooth, looping. Rain hiss bed + distant rolling rumble swelled by a
    // slow LFO. No sharp thunder claps so the loop never seams.
    if (mode === "storm") {
      const stormGain = ctx.createGain();
      stormGain.gain.value = 1.0;
      stormGain.connect(master);

      const rainBuf = ctx.createBuffer(1, 2 * ctx.sampleRate, ctx.sampleRate);
      const rd = rainBuf.getChannelData(0);
      for (let i = 0; i < rd.length; i++) rd[i] = Math.random() * 2 - 1;
      const rain = ctx.createBufferSource();
      rain.buffer = rainBuf;
      rain.loop = true;
      const rainHP = ctx.createBiquadFilter();
      rainHP.type = "highpass";
      rainHP.frequency.value = 700;
      const rainLP = ctx.createBiquadFilter();
      rainLP.type = "lowpass";
      rainLP.frequency.value = 6500;
      const rainGain = ctx.createGain();
      rainGain.gain.value = 0.5;
      rain.connect(rainHP);
      rainHP.connect(rainLP);
      rainLP.connect(rainGain);
      rainGain.connect(stormGain);
      rain.start();
      nodesToStop.push(rain);

      const rumbleBuf = ctx.createBuffer(1, 4 * ctx.sampleRate, ctx.sampleRate);
      const rud = rumbleBuf.getChannelData(0);
      let rlo = 0;
      for (let i = 0; i < rud.length; i++) {
        const w = Math.random() * 2 - 1;
        rlo = (rlo + 0.02 * w) / 1.02;
        rud[i] = rlo * 3.5;
      }
      const rumble = ctx.createBufferSource();
      rumble.buffer = rumbleBuf;
      rumble.loop = true;
      const rumbleLP = ctx.createBiquadFilter();
      rumbleLP.type = "lowpass";
      rumbleLP.frequency.value = 110;
      rumbleLP.Q.value = 0.7;
      const rumbleGain = ctx.createGain();
      rumbleGain.gain.value = 0.5;
      rumble.connect(rumbleLP);
      rumbleLP.connect(rumbleGain);
      rumbleGain.connect(stormGain);
      rumble.start();
      nodesToStop.push(rumble);

      const swell = ctx.createOscillator();
      swell.type = "sine";
      swell.frequency.value = 0.06;
      const swellDepth = ctx.createGain();
      swellDepth.gain.value = 0.45;
      swell.connect(swellDepth);
      swellDepth.connect(rumbleGain.gain);
      swell.start();
      nodesToStop.push(swell);
    }

    // ─── SOCK TORNADO (laundry) ───────────────────────────────────
    // Warm motor hum + a midband whoosh amplitude-modulated by a ~0.8 Hz
    // rotation LFO. Hypnotic tumble, seamless loop.
    if (mode === "laundry") {
      const laundryGain = ctx.createGain();
      laundryGain.gain.value = 1.0;
      laundryGain.connect(master);

      const humBuf = ctx.createBuffer(1, 2 * ctx.sampleRate, ctx.sampleRate);
      const hd = humBuf.getChannelData(0);
      let hlo = 0;
      for (let i = 0; i < hd.length; i++) {
        const w = Math.random() * 2 - 1;
        hlo = (hlo + 0.02 * w) / 1.02;
        hd[i] = hlo * 3.5;
      }
      const hum = ctx.createBufferSource();
      hum.buffer = humBuf;
      hum.loop = true;
      const humLP = ctx.createBiquadFilter();
      humLP.type = "lowpass";
      humLP.frequency.value = 320;
      const humGain = ctx.createGain();
      humGain.gain.value = 0.5;
      hum.connect(humLP);
      humLP.connect(humGain);
      humGain.connect(laundryGain);
      hum.start();
      nodesToStop.push(hum);

      const tumbleBuf = ctx.createBuffer(1, 2 * ctx.sampleRate, ctx.sampleRate);
      const td = tumbleBuf.getChannelData(0);
      for (let i = 0; i < td.length; i++) td[i] = Math.random() * 2 - 1;
      const tumble = ctx.createBufferSource();
      tumble.buffer = tumbleBuf;
      tumble.loop = true;
      const tumbleBP = ctx.createBiquadFilter();
      tumbleBP.type = "bandpass";
      tumbleBP.frequency.value = 480;
      tumbleBP.Q.value = 0.8;
      const tumbleGain = ctx.createGain();
      tumbleGain.gain.value = 0.28;
      tumble.connect(tumbleBP);
      tumbleBP.connect(tumbleGain);
      tumbleGain.connect(laundryGain);
      tumble.start();
      nodesToStop.push(tumble);

      const spin = ctx.createOscillator();
      spin.type = "sine";
      spin.frequency.value = 0.8;
      const spinDepth = ctx.createGain();
      spinDepth.gain.value = 0.26;
      spin.connect(spinDepth);
      spinDepth.connect(tumbleGain.gain);
      spin.start();
      nodesToStop.push(spin);
    }

    const resume = () => {
      ctx.resume().catch(() => {});
    };
    window.addEventListener("pointerdown", resume, { once: true });

    stopRef.current = () => {
      for (const n of nodesToStop) {
        try {
          n.stop();
        } catch {}
      }
      ctx.close().catch(() => {});
      window.removeEventListener("pointerdown", resume);
    };

    return () => {
      stopRef.current?.();
      stopRef.current = null;
    };
  }, [mode]);

  return null;
}
