"use client";

import { useEffect, useRef, useState } from "react";

/**
 * Focus audio. Eight modes, all generated by WebAudio so nothing to license or
 * host. Fixed master gain — the panel intentionally has no volume.
 *
 * Modes (driven by localStorage["sound"]):
 *   "off"      — silence
 *   "pink"     — pink noise (Paul Kellet filter), broad balanced spectrum
 *   "brown"    — brown noise (random walk + lowpass 800 Hz + slow tremolo)
 *   "binaural" — 40 Hz gamma binaural beat (200 Hz L / 240 Hz R + bed)
 *   "lofi"     — warm pad: 3 detuned saws → lowpass w/ slow LFO + vinyl crackle
 *   "drone"    — cinematic: sub 55 Hz + detuned sine octave + filtered air pad
 *   "sousvide" — circulator squeal + pump resonance + submerged water bed
 *   "blackhole"— gravitational sub-drone + orbital wobble + dark turbulence
 */
export type FocusMode =
  | "off"
  | "pink"
  | "brown"
  | "binaural"
  | "lofi"
  | "drone"
  | "sousvide"
  | "blackhole";

const VALID_MODES: FocusMode[] = [
  "off",
  "pink",
  "brown",
  "binaural",
  "lofi",
  "drone",
  "sousvide",
  "blackhole",
];

function readMode(): FocusMode {
  if (typeof window === "undefined") return "off";
  const raw = localStorage.getItem("sound");
  if (raw === "true" || raw === "noise") return "brown";
  if (raw === "isochronic") return "binaural";
  if (raw === "false" || raw === null) return "off";
  return (VALID_MODES as string[]).includes(raw) ? (raw as FocusMode) : "off";
}

export function FocusAudio() {
  const [mode, setMode] = useState<FocusMode>("off");
  const stopRef = useRef<(() => void) | null>(null);

  useEffect(() => {
    if (typeof window === "undefined") return;
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setMode(readMode());

    const sync = () => setMode(readMode());
    const handleStorage = (e: StorageEvent) => {
      if (e.key === "sound") sync();
    };
    window.addEventListener("storage", handleStorage);
    window.addEventListener("sound-toggle", sync);
    return () => {
      window.removeEventListener("storage", handleStorage);
      window.removeEventListener("sound-toggle", sync);
    };
  }, []);

  useEffect(() => {
    if (typeof window === "undefined") return;

    if (mode === "off") {
      stopRef.current?.();
      stopRef.current = null;
      return;
    }

    type WebkitWindow = Window & { webkitAudioContext?: typeof AudioContext };
    const Ctx =
      window.AudioContext ?? (window as WebkitWindow).webkitAudioContext;
    if (!Ctx) return;

    const ctx = new Ctx();
    const master = ctx.createGain();
    master.gain.value = 0.05;
    master.connect(ctx.destination);

    const nodesToStop: { stop: () => void }[] = [];

    // ─── PINK NOISE ────────────────────────────────────────────────
    if (mode === "pink") {
      const bufferSize = 2 * ctx.sampleRate;
      const buf = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
      const data = buf.getChannelData(0);
      // Paul Kellet's economy pink filter.
      let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0;
      for (let i = 0; i < bufferSize; i++) {
        const white = Math.random() * 2 - 1;
        b0 = 0.99886 * b0 + white * 0.0555179;
        b1 = 0.99332 * b1 + white * 0.0750759;
        b2 = 0.96900 * b2 + white * 0.1538520;
        b3 = 0.86650 * b3 + white * 0.3104856;
        b4 = 0.55000 * b4 + white * 0.5329522;
        b5 = -0.7616 * b5 - white * 0.0168980;
        data[i] = (b0 + b1 + b2 + b3 + b4 + b5 + b6 + white * 0.5362) * 0.11;
        b6 = white * 0.115926;
      }
      const noise = ctx.createBufferSource();
      noise.buffer = buf;
      noise.loop = true;
      const g = ctx.createGain();
      g.gain.value = 1.0;
      noise.connect(g);
      g.connect(master);
      noise.start();
      nodesToStop.push(noise);
    }

    // ─── BROWN NOISE ───────────────────────────────────────────────
    if (mode === "brown") {
      const bedGain = ctx.createGain();
      bedGain.gain.value = 1.0;
      bedGain.connect(master);

      const bufferSize = 2 * ctx.sampleRate;
      const buf = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
      const data = buf.getChannelData(0);
      let lastOut = 0;
      for (let i = 0; i < bufferSize; i++) {
        const white = Math.random() * 2 - 1;
        lastOut = (lastOut + 0.02 * white) / 1.02;
        data[i] = lastOut * 3.5;
      }
      const noise = ctx.createBufferSource();
      noise.buffer = buf;
      noise.loop = true;

      const lowpass = ctx.createBiquadFilter();
      lowpass.type = "lowpass";
      lowpass.frequency.value = 800;
      lowpass.Q.value = 0.7;

      const tremoloOsc = ctx.createOscillator();
      tremoloOsc.frequency.value = 0.08;
      const tremoloDepth = ctx.createGain();
      tremoloDepth.gain.value = 0.012;
      tremoloOsc.connect(tremoloDepth);
      tremoloDepth.connect(bedGain.gain);

      noise.connect(lowpass);
      lowpass.connect(bedGain);
      noise.start();
      tremoloOsc.start();
      nodesToStop.push(noise, tremoloOsc);
    }

    // ─── BINAURAL γ ────────────────────────────────────────────────
    if (mode === "binaural") {
      // Bed under the tonal beat for warmth.
      const bedGain = ctx.createGain();
      bedGain.gain.value = 0.45;
      bedGain.connect(master);

      const bufferSize = 2 * ctx.sampleRate;
      const buf = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
      const data = buf.getChannelData(0);
      let lastOut = 0;
      for (let i = 0; i < bufferSize; i++) {
        const white = Math.random() * 2 - 1;
        lastOut = (lastOut + 0.02 * white) / 1.02;
        data[i] = lastOut * 3.5;
      }
      const noise = ctx.createBufferSource();
      noise.buffer = buf;
      noise.loop = true;
      const lowpass = ctx.createBiquadFilter();
      lowpass.type = "lowpass";
      lowpass.frequency.value = 800;
      noise.connect(lowpass);
      lowpass.connect(bedGain);
      noise.start();
      nodesToStop.push(noise);

      // 40 Hz gamma: 200 Hz L / 240 Hz R.
      const merger = ctx.createChannelMerger(2);
      const toneGain = ctx.createGain();
      toneGain.gain.value = 0.55;
      merger.connect(toneGain);
      toneGain.connect(master);

      const left = ctx.createOscillator();
      left.frequency.value = 200;
      const leftGain = ctx.createGain();
      leftGain.gain.value = 1;
      left.connect(leftGain);
      leftGain.connect(merger, 0, 0);

      const right = ctx.createOscillator();
      right.frequency.value = 240;
      const rightGain = ctx.createGain();
      rightGain.gain.value = 1;
      right.connect(rightGain);
      rightGain.connect(merger, 0, 1);

      left.start();
      right.start();
      nodesToStop.push(left, right);
    }

    // ─── LO-FI PAD ─────────────────────────────────────────────────
    if (mode === "lofi") {
      // Warm pad: A2 root with detuned saw stack, lowpassed, slow filter LFO.
      // Root = 110 Hz (A2). Stack: -7c, +5c on top of root for chorus thickness.
      const padGain = ctx.createGain();
      padGain.gain.value = 0.5;
      const lowpass = ctx.createBiquadFilter();
      lowpass.type = "lowpass";
      lowpass.frequency.value = 1400;
      lowpass.Q.value = 1.2;
      padGain.connect(lowpass);
      lowpass.connect(master);

      const detunes = [-7, 0, 5];
      for (const cents of detunes) {
        const osc = ctx.createOscillator();
        osc.type = "sawtooth";
        osc.frequency.value = 110;
        osc.detune.value = cents;
        const g = ctx.createGain();
        g.gain.value = 0.33;
        osc.connect(g);
        g.connect(padGain);
        osc.start();
        nodesToStop.push(osc);
      }

      // Add a perfect 5th sub-octave for grounding.
      const sub = ctx.createOscillator();
      sub.type = "sine";
      sub.frequency.value = 55;
      const subGain = ctx.createGain();
      subGain.gain.value = 0.18;
      sub.connect(subGain);
      subGain.connect(master);
      sub.start();
      nodesToStop.push(sub);

      // Slow filter sweep LFO so the pad breathes.
      const lfo = ctx.createOscillator();
      lfo.type = "sine";
      lfo.frequency.value = 0.06;
      const lfoDepth = ctx.createGain();
      lfoDepth.gain.value = 500;
      lfo.connect(lfoDepth);
      lfoDepth.connect(lowpass.frequency);
      lfo.start();
      nodesToStop.push(lfo);

      // Sparse vinyl crackle: highpassed brown noise at low volume.
      const crackleBuf = ctx.createBuffer(1, ctx.sampleRate, ctx.sampleRate);
      const cd = crackleBuf.getChannelData(0);
      let last = 0;
      for (let i = 0; i < cd.length; i++) {
        const w = Math.random() * 2 - 1;
        last = (last + 0.02 * w) / 1.02;
        // Random pops on top of the bed.
        cd[i] = last * 2 + (Math.random() < 0.0002 ? (Math.random() * 2 - 1) * 0.4 : 0);
      }
      const crackle = ctx.createBufferSource();
      crackle.buffer = crackleBuf;
      crackle.loop = true;
      const hp = ctx.createBiquadFilter();
      hp.type = "highpass";
      hp.frequency.value = 1800;
      const cg = ctx.createGain();
      cg.gain.value = 0.18;
      crackle.connect(hp);
      hp.connect(cg);
      cg.connect(master);
      crackle.start();
      nodesToStop.push(crackle);
    }

    // ─── CINEMATIC DRONE ──────────────────────────────────────────
    if (mode === "drone") {
      const droneGain = ctx.createGain();
      droneGain.gain.value = 0.55;
      droneGain.connect(master);

      // Sub fundamental: A1.
      const sub = ctx.createOscillator();
      sub.type = "sine";
      sub.frequency.value = 55;
      const subGain = ctx.createGain();
      subGain.gain.value = 0.5;
      sub.connect(subGain);
      subGain.connect(droneGain);
      sub.start();
      nodesToStop.push(sub);

      // Detuned octave above for slow beating.
      const t1 = ctx.createOscillator();
      t1.type = "sine";
      t1.frequency.value = 110;
      const t1g = ctx.createGain();
      t1g.gain.value = 0.32;
      t1.connect(t1g);
      t1g.connect(droneGain);
      t1.start();
      nodesToStop.push(t1);

      const t2 = ctx.createOscillator();
      t2.type = "sine";
      t2.frequency.value = 110.6;
      const t2g = ctx.createGain();
      t2g.gain.value = 0.32;
      t2.connect(t2g);
      t2g.connect(droneGain);
      t2.start();
      nodesToStop.push(t2);

      // Air pad: bandpassed white noise that breathes.
      const airBufSize = 2 * ctx.sampleRate;
      const airBuf = ctx.createBuffer(1, airBufSize, ctx.sampleRate);
      const airData = airBuf.getChannelData(0);
      for (let i = 0; i < airBufSize; i++) airData[i] = Math.random() * 2 - 1;
      const air = ctx.createBufferSource();
      air.buffer = airBuf;
      air.loop = true;
      const bp = ctx.createBiquadFilter();
      bp.type = "bandpass";
      bp.frequency.value = 900;
      bp.Q.value = 3.5;
      const airGain = ctx.createGain();
      airGain.gain.value = 0.6;
      air.connect(bp);
      bp.connect(airGain);
      airGain.connect(droneGain);
      air.start();
      nodesToStop.push(air);

      // Very slow LFO on the bandpass for the breathing.
      const lfo = ctx.createOscillator();
      lfo.type = "sine";
      lfo.frequency.value = 0.04;
      const lfoDepth = ctx.createGain();
      lfoDepth.gain.value = 400;
      lfo.connect(lfoDepth);
      lfoDepth.connect(bp.frequency);
      lfo.start();
      nodesToStop.push(lfo);
    }

    // ─── SOUS VIDE CIRCULATOR ─────────────────────────────────────
    if (mode === "sousvide") {
      const bed = ctx.createGain();
      bed.gain.value = 0.42;
      bed.connect(master);

      // The high, steady mechanical note from the approved Anova reference.
      for (const [frequency, gain] of [[4320, 0.24], [4284, 0.09]] as const) {
        const tone = ctx.createOscillator();
        tone.type = "sine";
        tone.frequency.value = frequency;
        const toneGain = ctx.createGain();
        toneGain.gain.value = gain;
        tone.connect(toneGain);
        toneGain.connect(bed);
        tone.start();
        nodesToStop.push(tone);
      }

      // Pump body resonance under the squeal.
      const pump = ctx.createOscillator();
      pump.type = "triangle";
      pump.frequency.value = 118;
      const pumpGain = ctx.createGain();
      pumpGain.gain.value = 0.2;
      pump.connect(pumpGain);
      pumpGain.connect(bed);
      pump.start();
      nodesToStop.push(pump);

      // Submerged water bed. The buffer loops continuously; there is no chime.
      const waterBuffer = ctx.createBuffer(1, 4 * ctx.sampleRate, ctx.sampleRate);
      const waterData = waterBuffer.getChannelData(0);
      for (let i = 0; i < waterData.length; i++) {
        waterData[i] = (Math.random() * 2 - 1) * 0.28;
      }
      const water = ctx.createBufferSource();
      water.buffer = waterBuffer;
      water.loop = true;
      const waterFilter = ctx.createBiquadFilter();
      waterFilter.type = "bandpass";
      waterFilter.frequency.value = 520;
      waterFilter.Q.value = 0.65;
      water.connect(waterFilter);
      waterFilter.connect(bed);
      water.start();
      nodesToStop.push(water);
    }

    // ─── BLACK HOLE ────────────────────────────────────────────────
    if (mode === "blackhole") {
      const gravity = ctx.createGain();
      gravity.gain.value = 0.72;
      gravity.connect(master);

      for (const [frequency, gain] of [[32, 0.7], [48.2, 0.28], [64.35, 0.16]] as const) {
        const core = ctx.createOscillator();
        core.type = "sine";
        core.frequency.value = frequency;
        const coreGain = ctx.createGain();
        coreGain.gain.value = gain;
        core.connect(coreGain);
        coreGain.connect(gravity);
        core.start();
        nodesToStop.push(core);
      }

      const turbulenceBuffer = ctx.createBuffer(1, 4 * ctx.sampleRate, ctx.sampleRate);
      const turbulenceData = turbulenceBuffer.getChannelData(0);
      let last = 0;
      for (let i = 0; i < turbulenceData.length; i++) {
        last = (last + 0.018 * (Math.random() * 2 - 1)) / 1.018;
        turbulenceData[i] = last * 3;
      }
      const turbulence = ctx.createBufferSource();
      turbulence.buffer = turbulenceBuffer;
      turbulence.loop = true;
      const darkFilter = ctx.createBiquadFilter();
      darkFilter.type = "lowpass";
      darkFilter.frequency.value = 260;
      const turbulenceGain = ctx.createGain();
      turbulenceGain.gain.value = 0.48;
      turbulence.connect(darkFilter);
      darkFilter.connect(turbulenceGain);
      turbulenceGain.connect(gravity);
      turbulence.start();
      nodesToStop.push(turbulence);

      const orbit = ctx.createOscillator();
      orbit.type = "sine";
      orbit.frequency.value = 0.055;
      const orbitDepth = ctx.createGain();
      orbitDepth.gain.value = 0.18;
      orbit.connect(orbitDepth);
      orbitDepth.connect(gravity.gain);
      orbit.start();
      nodesToStop.push(orbit);
    }

    const resume = () => {
      ctx.resume().catch(() => {});
    };
    window.addEventListener("pointerdown", resume, { once: true });

    stopRef.current = () => {
      for (const n of nodesToStop) {
        try {
          n.stop();
        } catch {}
      }
      ctx.close().catch(() => {});
      window.removeEventListener("pointerdown", resume);
    };

    return () => {
      stopRef.current?.();
      stopRef.current = null;
    };
  }, [mode]);

  return null;
}
