"use client";

import { useEffect, useRef, useState } from "react";

/**
 * Focus audio. Four modes, all generated by WebAudio so there's nothing to
 * license or host. Fixed master gain — the panel intentionally has no volume.
 *
 * Modes (driven by localStorage["sound"]):
 *   "off"        — silence
 *   "noise"      — brown-noise pad, 800Hz lowpass, slow 12s tremolo
 *   "binaural"   — 40Hz gamma binaural beat (200Hz L / 240Hz R + bed)
 *   "isochronic" — 10Hz alpha isochronic pulse on a 200Hz carrier + bed
 *
 * The MobileTopBar + NavRail sound picker writes the mode to localStorage and
 * dispatches a `sound-toggle` CustomEvent so this component re-syncs without
 * a reload.
 */
export type FocusMode = "off" | "noise" | "binaural" | "isochronic";

const VALID_MODES: FocusMode[] = ["off", "noise", "binaural", "isochronic"];

function readMode(): FocusMode {
  if (typeof window === "undefined") return "off";
  const raw = localStorage.getItem("sound");
  // Backwards compat with the old boolean toggle.
  if (raw === "true") return "noise";
  if (raw === "false" || raw === null) return "off";
  return (VALID_MODES as string[]).includes(raw) ? (raw as FocusMode) : "off";
}

export function FocusAudio() {
  const [mode, setMode] = useState<FocusMode>("off");
  const stopRef = useRef<(() => void) | null>(null);

  useEffect(() => {
    if (typeof window === "undefined") return;
    setMode(readMode());

    const sync = () => setMode(readMode());
    const handleStorage = (e: StorageEvent) => {
      if (e.key === "sound") sync();
    };
    window.addEventListener("storage", handleStorage);
    window.addEventListener("sound-toggle", sync);
    return () => {
      window.removeEventListener("storage", handleStorage);
      window.removeEventListener("sound-toggle", sync);
    };
  }, []);

  useEffect(() => {
    if (typeof window === "undefined") return;

    if (mode === "off") {
      stopRef.current?.();
      stopRef.current = null;
      return;
    }

    type WebkitWindow = Window & { webkitAudioContext?: typeof AudioContext };
    const Ctx =
      window.AudioContext ?? (window as WebkitWindow).webkitAudioContext;
    if (!Ctx) return;

    const ctx = new Ctx();
    const master = ctx.createGain();
    master.gain.value = 0.04;
    master.connect(ctx.destination);

    const nodesToStop: { stop: () => void }[] = [];

    if (mode === "noise" || mode === "binaural" || mode === "isochronic") {
      // Shared brown-noise bed for warmth. Quieter under the tonal modes.
      const bedGain = ctx.createGain();
      bedGain.gain.value = mode === "noise" ? 1.0 : 0.45;
      bedGain.connect(master);

      const bufferSize = 2 * ctx.sampleRate;
      const buf = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
      const data = buf.getChannelData(0);
      let lastOut = 0;
      for (let i = 0; i < bufferSize; i++) {
        const white = Math.random() * 2 - 1;
        lastOut = (lastOut + 0.02 * white) / 1.02;
        data[i] = lastOut * 3.5;
      }
      const noise = ctx.createBufferSource();
      noise.buffer = buf;
      noise.loop = true;

      const lowpass = ctx.createBiquadFilter();
      lowpass.type = "lowpass";
      lowpass.frequency.value = 800;
      lowpass.Q.value = 0.7;

      // Slow tremolo on the bed (noise-mode signature).
      const tremoloOsc = ctx.createOscillator();
      tremoloOsc.frequency.value = 0.08;
      const tremoloDepth = ctx.createGain();
      tremoloDepth.gain.value = mode === "noise" ? 0.012 : 0.006;
      tremoloOsc.connect(tremoloDepth);
      tremoloDepth.connect(bedGain.gain);

      noise.connect(lowpass);
      lowpass.connect(bedGain);
      noise.start();
      tremoloOsc.start();
      nodesToStop.push(noise, tremoloOsc);
    }

    if (mode === "binaural") {
      // 40Hz gamma beat: 200Hz left, 240Hz right.
      const merger = ctx.createChannelMerger(2);
      const toneGain = ctx.createGain();
      toneGain.gain.value = 0.55;
      merger.connect(toneGain);
      toneGain.connect(master);

      const left = ctx.createOscillator();
      left.frequency.value = 200;
      const leftGain = ctx.createGain();
      leftGain.gain.value = 1;
      left.connect(leftGain);
      leftGain.connect(merger, 0, 0);

      const right = ctx.createOscillator();
      right.frequency.value = 240;
      const rightGain = ctx.createGain();
      rightGain.gain.value = 1;
      right.connect(rightGain);
      rightGain.connect(merger, 0, 1);

      left.start();
      right.start();
      nodesToStop.push(left, right);
    }

    if (mode === "isochronic") {
      // 10Hz alpha pulse: 200Hz carrier amplitude-modulated by a 10Hz LFO.
      const carrier = ctx.createOscillator();
      carrier.frequency.value = 200;

      const amp = ctx.createGain();
      amp.gain.value = 0; // LFO drives this between 0 and 0.6

      const lfo = ctx.createOscillator();
      lfo.type = "sine";
      lfo.frequency.value = 10;
      const lfoDepth = ctx.createGain();
      lfoDepth.gain.value = 0.3;
      lfo.connect(lfoDepth);
      lfoDepth.connect(amp.gain);

      const offset = ctx.createConstantSource();
      offset.offset.value = 0.3;
      offset.connect(amp.gain);

      const toneGain = ctx.createGain();
      toneGain.gain.value = 0.45;

      carrier.connect(amp);
      amp.connect(toneGain);
      toneGain.connect(master);

      carrier.start();
      lfo.start();
      offset.start();
      nodesToStop.push(carrier, lfo, offset);
    }

    const resume = () => {
      ctx.resume().catch(() => {});
    };
    window.addEventListener("pointerdown", resume, { once: true });

    stopRef.current = () => {
      for (const n of nodesToStop) {
        try {
          n.stop();
        } catch {}
      }
      ctx.close().catch(() => {});
      window.removeEventListener("pointerdown", resume);
    };

    return () => {
      stopRef.current?.();
      stopRef.current = null;
    };
  }, [mode]);

  return null;
}
